import { useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Activity, ArrowDown, ArrowUpRight, Brain, CheckCircle2, Clock3, Gauge, Radar, Target, TrendingUp, Zap } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useAuth } from '../context/AuthContext';
import { useData } from '../context/DataContext';
import { Badge, Card, MetricCard, PageHeading, PageTransition, ProgressBar, SectionTitle } from '../components/ui';
import { ReactionChart, ScoreHistoryChart, SkillBars, SkillRadar } from '../components/Charts';
import type { Mission, SkillKey, UserProfile } from '../types';
import { SKILL_LABELS } from '../types';

const tooltip = { background: '#111b27', border: '1px solid #2b3d4d', borderRadius: 9, color: '#eaf2f5', fontSize: 12 };
const difficultyRank: Record<string, number> = { BEGINNER: 1, INTERMEDIATE: 2, ADVANCED: 3, EXPERT: 4 };

export default function AnalyticsPage() {
  const { user } = useAuth();
  const { db } = useData();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [selectedUserId, setSelectedUserId] = useState(user?.role === 'TRAINEE' ? user.uid : searchParams.get('trainee') ?? '');
  const [range, setRange] = useState<'30' | '90' | 'ALL'>('30');
  if (!user) return null;
  const trainees = db.users.filter((profile) => profile.role === 'TRAINEE');
  const profileSelect = user.role !== 'TRAINEE';
  const isAggregate = profileSelect && !selectedUserId;
  const selectedTrainee = trainees.find((profile) => profile.uid === selectedUserId);
  const activeUser = user.role === 'TRAINEE' ? user : selectedTrainee ?? (isAggregate ? aggregateProfile(trainees, user) : user);
  const missionPool = db.missions.filter((mission) => isAggregate ? mission.status === 'COMPLETED' : mission.userId === activeUser.uid);
  const cutoff = range === 'ALL' ? 0 : Date.now() - Number(range) * 86400000;
  const missions = missionPool.filter((mission) => mission.status === 'COMPLETED' && new Date(mission.completedAt ?? mission.createdAt).getTime() >= cutoff).sort((a, b) => (a.completedAt ?? a.createdAt).localeCompare(b.completedAt ?? b.createdAt));
  const allMissions = missionPool.filter((mission) => mission.status === 'COMPLETED').sort((a, b) => (a.completedAt ?? a.createdAt).localeCompare(b.completedAt ?? b.createdAt));
  const avgScore = missions.length ? Math.round(missions.reduce((sum, mission) => sum + (mission.score ?? 0), 0) / missions.length) : activeUser.overallScore;
  const weakKey = weakest(activeUser.skills);
  const accuracyData = missions.map((mission, index) => ({ name: `M${index + 1}`, value: mission.categoryScores?.accuracy ?? 0, label: mission.title }));
  const activeRangeLabel = range === 'ALL' ? 'ALL-TIME' : `LAST ${range} DAYS`;
  const heatmapMissions = [...allMissions].slice(-6).reverse();
  const heatKeys: SkillKey[] = ['detection', 'tracking', 'navigation', 'accuracy', 'reactionTime', 'decisionMaking', 'situationalAwareness'];
  const difficulties = allMissions.slice(-8);

  return <PageTransition><PageHeading eyebrow="PERFORMANCE INTELLIGENCE / SKILL PROFILE" title="Skill analytics" description={profileSelect ? 'Compare trainee performance, review skill gaps, and monitor difficulty progression.' : 'Track the skill dimensions that matter, session by session.'} action={<div className="analytics-heading-controls">{profileSelect && <label className="select-field compact-select"><span className="field-label">TRAINEE PROFILE</span><select value={selectedUserId} onChange={(event) => setSelectedUserId(event.target.value)}><option value="">All trainees (aggregate)</option>{trainees.map((profile) => <option key={profile.uid} value={profile.uid}>{profile.name}</option>)}</select></label>}<div className="range-switch">{(['30', '90', 'ALL'] as const).map((item) => <button key={item} className={range === item ? 'range-active' : ''} onClick={() => setRange(item)}>{item === 'ALL' ? 'ALL TIME' : `${item}D`}</button>)}</div></div>} />
    {isAggregate && <div className="analytics-aggregate-note"><Activity size={15} /><span>Showing aggregate cohort data for <b>{trainees.length} fictional trainees</b>. Select a trainee profile to view an individual skill passport.</span></div>}
    <div className="analytics-metrics"><MetricCard label="READINESS SCORE" value={activeUser.overallScore} unit="/100" trend={missions.length > 1 ? `${missions.length} sessions in range` : undefined} icon={Gauge} accent="cyan" detail="Current profile" /><MetricCard label="MISSION AVG." value={avgScore} unit="/100" icon={Target} accent="green" detail={activeRangeLabel} /><MetricCard label="AVG. RESPONSE" value={activeUser.averageReactionMs ? (activeUser.averageReactionMs / 1000).toFixed(1) : '—'} unit="s" icon={Zap} accent="orange" detail="Recorded training interval" /><MetricCard label="COMPLETION RATE" value={`${activeUser.successRate}%`} icon={CheckCircle2} accent="green" detail="Score threshold ≥ 65" /></div>
    <div className="analytics-main-grid"><Card className="analytics-radar-card"><div className="chart-panel-header"><div><div className="panel-overline">CURRENT PROFILE / 01</div><h2>Skill radar</h2><p>Multi-domain readiness overview.</p></div><Badge tone="cyan">{activeUser.trainingLevel}</Badge></div><SkillRadar skills={activeUser.skills} /><div className="radar-legend-row"><span><i className="legend-dot cyan-dot" /> CURRENT PROFILE</span><span>7 SKILL DIMENSIONS</span></div></Card><Card className="analytics-history-card"><div className="chart-panel-header"><div><div className="panel-overline">PERFORMANCE / 02</div><h2>Mission score history</h2><p>Recent completed sessions · {activeRangeLabel}</p></div><Badge>{missions.length} SESSIONS</Badge></div><ScoreHistoryChart missions={missions} /><div className="analytics-chart-foot"><span><i className="legend-dot cyan-dot" /> Score</span><span>DIFFICULTY SHOWN IN SESSION LOG</span></div></Card></div>
    <div className="analytics-charts-grid"><Card className="analytics-response-card"><SectionTitle title="Response interval" detail="Recorded first-response timing by session" /><ReactionChart missions={missions} /><div className="analytics-insight"><Zap size={14} /><span>Lower response intervals are useful when paired with accurate context checks.</span></div></Card><Card className="analytics-accuracy-card"><SectionTitle title="Accuracy trend" detail="Classification and confirmation score" /><div className="accuracy-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={accuracyData.length ? accuracyData : [{ name: '—', value: activeUser.skills.accuracy, label: 'Current profile' }]} margin={{ top: 12, right: 10, left: -22, bottom: 0 }}><CartesianGrid stroke="#25333f" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#738495', fontSize: 10, fontFamily: 'IBM Plex Mono, monospace' }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fill: '#738495', fontSize: 10, fontFamily: 'IBM Plex Mono, monospace' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} formatter={(value: number) => [`${value}%`, 'Accuracy']} /><Line type="monotone" dataKey="value" stroke="#f0a45d" strokeWidth={2.3} dot={{ r: 3.5, fill: '#f0a45d', stroke: '#111b27', strokeWidth: 1 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div><div className="analytics-insight orange-insight"><Target size={14} /><span>Current accuracy: <b>{activeUser.skills.accuracy}%</b>. Priority gap: <b>{SKILL_LABELS[weakKey]}</b>.</span></div></Card></div>
    <div className="analytics-lower-grid"><Card className="analytics-skill-bars-card"><div className="chart-panel-header"><div><div className="panel-overline">SKILL PROFILE / 03</div><h2>Domain performance</h2><p>Individual dimension scores.</p></div></div><SkillBars skills={activeUser.skills} /><div className="priority-skill-note"><span className="priority-icon"><ArrowDown size={14} /></span><span><small>PRIORITY GAP</small><b>{SKILL_LABELS[weakKey]} · {activeUser.skills[weakKey]}%</b></span><button onClick={() => navigate(`/missions/generate?objective=${encodeURIComponent(objectiveFromSkill(weakKey))}`)}>BUILD PRACTICE <ArrowUpRight size={13} /></button></div></Card><Card className="skill-heatmap-card"><SectionTitle title="Skill gap heatmap" detail="Session dimension scores · most recent at top" /><div className="heatmap-grid"><div className="heatmap-row heatmap-head"><span>MISSION</span>{heatKeys.map((key) => <span key={key} title={SKILL_LABELS[key]}>{shortName(key)}</span>)}</div>{heatmapMissions.length ? heatmapMissions.map((mission) => <div className="heatmap-row" key={mission.id}><span className="heatmap-mission" title={mission.title}>{mission.title.length > 18 ? `${mission.title.slice(0, 16)}…` : mission.title}</span>{heatKeys.map((key) => { const value = mission.categoryScores?.[key] ?? 0; return <span key={key} title={`${SKILL_LABELS[key]}: ${value}%`} className={`heat-cell ${heatTone(value)}`}>{value}</span>; })}</div>) : <div className="heatmap-empty">Complete a simulation to fill your skill heatmap.</div>}</div><div className="heatmap-legend"><span>NEEDS PRACTICE</span><i className="heat-low" /><i className="heat-mid" /><i className="heat-high" /><span>STRONG</span></div></Card></div>
    <Card className="difficulty-progression-card"><div className="chart-panel-header"><div><div className="panel-overline">ADAPTIVE TRAINING / 04</div><h2>Difficulty progression</h2><p>Procedural complexity across completed sessions.</p></div><span className="difficulty-auto-chip"><span /> AUTO-ADJUSTED</span></div><div className="difficulty-track">{difficulties.length ? difficulties.map((mission, index) => { const rank = difficultyRank[mission.difficulty] ?? 1; return <div className="difficulty-entry" key={mission.id} style={{ '--rank': rank } as React.CSSProperties}><div className="difficulty-bar-col"><span className="difficulty-score">{mission.score}</span><i className={`difficulty-bar difficulty-rank-${rank}`} style={{ height: `${28 + rank * 18}px` }} /><span className="difficulty-mission-index">M{index + 1}</span></div><div className="difficulty-tooltip"><b>{mission.title}</b><span>{mission.difficulty} · {mission.score}/100</span></div></div>; }) : <div className="difficulty-empty">Your completed missions will build a progression view here.</div>}</div><div className="difficulty-axis"><span>EARLIER SESSION</span><span>MISSION COMPLEXITY / SCORE IN BAR</span><span>MOST RECENT</span></div></Card>
  </PageTransition>;
}

function aggregateProfile(trainees: UserProfile[], base: UserProfile): UserProfile {
  const members = trainees.length ? trainees : [base];
  const avg = (pick: (profile: UserProfile) => number) => Math.round(members.reduce((sum, profile) => sum + pick(profile), 0) / members.length);
  const skills = {} as UserProfile['skills'];
  (Object.keys(SKILL_LABELS) as SkillKey[]).forEach((key) => { skills[key] = avg((profile) => profile.skills[key]); });
  return { ...base, uid: 'cohort-aggregate', name: 'Trainee cohort', email: '', role: 'TRAINEE', overallScore: avg((profile) => profile.overallScore), missionsCompleted: members.reduce((sum, profile) => sum + profile.missionsCompleted, 0), successRate: avg((profile) => profile.successRate), averageReactionMs: avg((profile) => profile.averageReactionMs), skills, trainingLevel: 'INTERMEDIATE' };
}

function weakest(skills: Record<string, number>): SkillKey { return (Object.keys(SKILL_LABELS) as SkillKey[]).filter((key) => key !== 'objectiveCompletion').reduce((weak, key) => skills[key] < skills[weak] ? key : weak, 'detection'); }
function objectiveFromSkill(skill: SkillKey) { return skill === 'reactionTime' ? 'Response Timing' : skill === 'navigation' ? 'Navigation' : skill === 'tracking' ? 'Tracking' : skill === 'accuracy' || skill === 'decisionMaking' ? 'Threat Classification' : skill === 'situationalAwareness' ? 'Situational Awareness' : 'Detection'; }
function shortName(key: SkillKey) { return key === 'situationalAwareness' ? 'SA' : key === 'decisionMaking' ? 'DM' : key === 'reactionTime' ? 'RT' : key === 'objectiveCompletion' ? 'OBJ' : key.slice(0, 3).toUpperCase(); }
function heatTone(value: number) { return value >= 85 ? 'heat-strong' : value >= 70 ? 'heat-good' : value >= 55 ? 'heat-mid' : 'heat-low'; }
