import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, BadgeCheck, BookOpenCheck, CalendarDays, CheckCircle2, Download, FileCheck2, Printer, ShieldCheck, Sparkles, Target } from 'lucide-react';
import { Avatar, Badge, Button, Card, PageHeading, PageTransition, ProgressBar, ScoreRing, SectionTitle } from '../components/ui';
import { SkillRadar } from '../components/Charts';
import { useAuth } from '../context/AuthContext';
import { useData } from '../context/DataContext';
import { useToast } from '../context/ToastContext';
import type { Certification, SkillKey } from '../types';
import { SKILL_LABELS } from '../types';

export default function PassportPage() {
  const { user } = useAuth();
  const { db } = useData();
  const { toast } = useToast();
  const navigate = useNavigate();
  const [selectedCertificate, setSelectedCertificate] = useState<Certification | null>(null);
  const certifications = db.certifications.filter((cert) => cert.userId === user?.uid).sort((a, b) => (b.issueDate ?? '').localeCompare(a.issueDate ?? ''));
  const certThreshold = db.systemSettings.certificationThreshold;
  const earned = certifications.filter((cert) => cert.status === 'EARNED');
  const weakest = (Object.keys(SKILL_LABELS) as SkillKey[]).filter((key) => key !== 'objectiveCompletion').reduce((a, b) => user && user.skills[a] < user.skills[b] ? a : b, 'detection');
  if (!user) return null;
  const issueDate = earned[0]?.issueDate ?? user.baselineCompletedAt ?? user.createdAt;
  const printCertificate = (certificate: Certification) => { setSelectedCertificate(certificate); window.setTimeout(() => { window.print(); toast('Use your browser print dialog to save a PDF copy.', 'info'); }, 120); };
  const printPassport = () => { setSelectedCertificate(null); window.setTimeout(() => { window.print(); toast('Use your browser print dialog to save your passport as PDF.', 'info'); }, 120); };

  return <PageTransition><PageHeading eyebrow="TRAINEE RECORD / DIGITAL PASSPORT" title="Skill passport" description="A portable record of your simulated training history, readiness, and earned credentials." action={<Button variant="secondary" onClick={printPassport}><Printer size={14} /> PRINT SKILL PASSPORT</Button>} />
    <div className="passport-layout"><div className="passport-main"><Card className="passport-hero-card"><div className="passport-watermark"><ShieldCheck size={172} /></div><div className="passport-topline"><div className="passport-brand"><span className="brand-mark"><BookOpenCheck size={18} /></span><span>SKYHAWK ARENA <small>DIGITAL SKILL PASSPORT</small></span></div><Badge tone="cyan">SIMULATION TRAINING RECORD</Badge></div><div className="passport-profile"><Avatar name={user.name} size="lg" photoURL={user.photoURL} /><div><span>TRAINEE PROFILE / SHA-26-{user.uid.slice(-4).toUpperCase()}</span><h2>{user.name}</h2><p>{user.email}</p></div><div className="passport-score"><span>READINESS</span><b>{user.overallScore}<small>/100</small></b></div></div><div className="passport-stats"><div><span>TRAINING LEVEL</span><b>{user.trainingLevel}</b></div><div><span>MISSIONS COMPLETED</span><b>{user.missionsCompleted}</b></div><div><span>SUCCESS RATE</span><b>{user.successRate}%</b></div><div><span>CURRENT CREDENTIAL</span><b>{user.certificationStatus.split('•')[0].trim()}</b></div></div><div className="passport-divider" /><div className="passport-footline"><span><CalendarDays size={13} /> RECORD STARTED {new Date(user.createdAt).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' }).toUpperCase()}</span><span><ShieldCheck size={13} /> VERIFIED TRAINING PROFILE</span><span>SIH 2026 / PROTOTYPE</span></div></Card>
      <div className="passport-lower-grid"><Card className="passport-skills-card"><SectionTitle title="Verified skill profile" detail="Current readiness across core dimensions" /><div className="passport-radar-wrap"><SkillRadar skills={user.skills} compact /></div><div className="passport-skill-list">{(['detection', 'tracking', 'navigation', 'accuracy', 'reactionTime', 'decisionMaking', 'situationalAwareness'] as SkillKey[]).map((key) => <div key={key}><span>{SKILL_LABELS[key]}</span><ProgressBar value={user.skills[key]} color={user.skills[key] >= 85 ? 'green' : user.skills[key] < 65 ? 'orange' : 'cyan'} /><b>{user.skills[key]}%</b></div>)}</div></Card><Card className="passport-credential-card"><div className="credential-card-header"><span className="credential-emblem"><BadgeCheck size={22} /></span><div><span className="panel-overline">CREDENTIAL STATUS</span><h3>{earned.length ? 'Certification earned' : 'Certification in progress'}</h3></div></div>{earned.length ? <div className="credential-earned-detail"><span className="credential-tier">{earned[0].tier}</span><b>{earned[0].name}</b><p>{earned[0].description}</p><div><span>CREDENTIAL ID</span><code>{earned[0].credentialId}</code></div><div><span>ISSUE DATE</span><b>{earned[0].issueDate ? new Date(earned[0].issueDate).toLocaleDateString() : '—'}</b></div></div> : <div className="credential-progress-detail"><p>Complete a baseline assessment and record three training missions with an overall score of {certThreshold} or above.</p><div className="credential-progress-row"><span>MISSIONS</span><b>{Math.min(user.missionsCompleted, 3)} / 3</b></div><ProgressBar value={Math.min(100, user.missionsCompleted / 3 * 100)} color="orange" /><div className="credential-progress-row"><span>READINESS TARGET</span><b>{user.overallScore} / {certThreshold}</b></div><ProgressBar value={Math.min(100, user.overallScore / certThreshold * 100)} color="orange" /><Button variant="secondary" onClick={() => navigate(user.baselineCompleted ? '/missions/generate' : '/assessment')}>CONTINUE TRAINING <ArrowRight size={13} /></Button></div>}
        {earned.length > 0 && <Button className="credential-download" onClick={() => printCertificate(earned[0])}><Download size={14} /> DOWNLOAD CERTIFICATE / PDF</Button>}</Card></div>
      <Card className="passport-history-card"><SectionTitle title="Credential history" detail="Issued and in-progress training credentials" />{certifications.length ? certifications.map((certificate) => <div className="passport-certificate-row" key={certificate.id}><span className={`certificate-row-icon ${certificate.status === 'EARNED' ? 'cert-icon-earned' : ''}`}><FileCheck2 size={17} /></span><span className="certificate-row-copy"><b>{certificate.name}</b><small>{certificate.description}</small></span><Badge tone={certificate.status === 'EARNED' ? 'green' : 'orange'}>{certificate.status}</Badge>{certificate.status === 'EARNED' && <button className="table-action" aria-label={`Print ${certificate.name}`} onClick={() => printCertificate(certificate)}><Download size={14} /></button>}</div>) : <div className="passport-no-certs"><Sparkles size={17} /><span>Certification progress will appear here after your baseline and mission reviews.</span></div>}</Card></div>
      <aside className="passport-side"><Card className="passport-score-card"><div className="panel-overline">READINESS INDEX</div><ScoreRing score={user.overallScore} size={150} /><span className="passport-level-badge">{user.trainingLevel} LEVEL</span><p>Profile updated after {user.missionsCompleted} mission records.</p><Button variant="secondary" onClick={() => navigate('/analytics')}>VIEW ANALYTICS <ArrowRight size={13} /></Button></Card><Card className="passport-gap-card"><div className="gap-card-icon"><Target size={17} /></div><div className="panel-overline">DEVELOPMENT FOCUS</div><h3>{SKILL_LABELS[weakest]}</h3><p>Your lowest current skill dimension is a recommended focus for the next adaptive session.</p><div className="gap-score-row"><span>CURRENT SCORE</span><b>{user.skills[weakest]}%</b></div><ProgressBar value={user.skills[weakest]} color="orange" /><Button size="sm" onClick={() => navigate('/missions/generate')}>BUILD PRACTICE MISSION <ArrowRight size={13} /></Button></Card><div className="passport-privacy-note"><ShieldCheck size={14} /><span>Passport data belongs to your profile. Instructors can review authorized training records.</span></div></aside></div>
    <div className="print-certificate" aria-hidden="true"><div className="print-cert-border"><div className="print-cert-top"><span>SKYHAWK ARENA</span><span>SIH 2026 / TRAINING RECORD</span></div><div className="print-cert-mark"><ShieldCheck size={40} /></div><span className="print-cert-kicker">CERTIFICATE OF SIMULATED TRAINING</span><h1>{selectedCertificate?.name ?? 'Digital Skill Passport'}</h1><p className="print-cert-presented">This record is presented to</p><h2>{user.name}</h2><p className="print-cert-description">{selectedCertificate?.description ?? 'Trainee digital skill passport and fictional simulation training readiness record.'}</p><div className="print-cert-stats"><div><span>TRAINING LEVEL</span><b>{user.trainingLevel}</b></div><div><span>OVERALL READINESS</span><b>{selectedCertificate?.score ?? user.overallScore} / 100</b></div><div><span>MISSIONS COMPLETED</span><b>{user.missionsCompleted}</b></div></div><div className="print-cert-signature"><div><b>{selectedCertificate?.issueDate ? new Date(selectedCertificate.issueDate).toLocaleDateString() : new Date(issueDate).toLocaleDateString()}</b><span>ISSUE DATE</span></div><div className="signature-mark">SKYHAWK<span>TRAINING SYSTEM</span></div><div><b>{selectedCertificate?.credentialId ?? `SHA-26-${user.uid.slice(-6).toUpperCase()}`}</b><span>CREDENTIAL ID</span></div></div><div className="print-cert-footer">SIMULATION TRAINING ONLY · FICTIONAL SCENARIOS · NOT AN OPERATIONAL QUALIFICATION</div></div></div>
  </PageTransition>;
}

export function CertificationsPage() {
  const { user } = useAuth();
  const { db } = useData();
  const navigate = useNavigate();
  const certs = db.certifications.filter((certificate) => certificate.userId === user?.uid);
  const certThreshold = db.systemSettings.certificationThreshold;
  if (!user) return null;
  const earned = certs.filter((item) => item.status === 'EARNED');
  return <PageTransition><PageHeading eyebrow="CREDENTIALS / TRAINING RECORD" title="Certifications" description="Track your earned simulation credentials and the next readiness milestone." action={<Button variant="secondary" onClick={() => navigate('/passport')}><BookOpenCheck size={14} /> OPEN SKILL PASSPORT</Button>} />
    <div className="certifications-summary"><div className="cert-summary-emblem"><BadgeCheck size={25} /></div><div><div className="panel-overline">CURRENT CERTIFICATION STATUS</div><h2>{earned.length ? earned[0].name : 'Certification pathway'}</h2><p>{earned.length ? `Issued ${earned[0].issueDate ? new Date(earned[0].issueDate).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' }) : '—'} · ${earned[0].credentialId}` : 'Complete baseline training and continue adaptive practice to work toward your first credential.'}</p></div><Badge tone={earned.length ? 'green' : 'orange'} dot>{earned.length ? 'EARNED' : 'IN PROGRESS'}</Badge></div>
    <div className="certification-grid">{certs.length ? certs.map((certificate) => <div className="certification-card" key={certificate.id}><div className="certification-card-top"><span className={`certification-icon ${certificate.status === 'EARNED' ? 'certification-earned' : ''}`}><ShieldCheck size={22} /></span><Badge tone={certificate.status === 'EARNED' ? 'green' : 'orange'}>{certificate.status}</Badge></div><div className="panel-overline">{certificate.tier} TRACK</div><h3>{certificate.name}</h3><p>{certificate.description}</p><div className="certification-card-meta"><span>CREDENTIAL ID</span><code>{certificate.credentialId}</code></div>{certificate.status === 'EARNED' ? <Button variant="secondary" onClick={() => navigate('/passport')}>VIEW / DOWNLOAD <ArrowRight size={13} /></Button> : <Button onClick={() => navigate(user.baselineCompleted ? '/missions/generate' : '/assessment')}>CONTINUE PATHWAY <ArrowRight size={13} /></Button>}</div>) : <Card className="certification-empty"><span className="certification-empty-icon"><ShieldCheck size={22} /></span><h3>Your credentials start here.</h3><p>Complete a baseline assessment, record three missions, and reach a readiness score of {certThreshold} to earn Simulation Foundations.</p><Button onClick={() => navigate(user.baselineCompleted ? '/missions/generate' : '/assessment')}>{user.baselineCompleted ? 'GENERATE MISSION' : 'START BASELINE'} <ArrowRight size={14} /></Button></Card>}</div>
    <Card className="cert-path-card"><div className="panel-overline">FOUNDATION PATHWAY</div><h2>Simulation Foundations</h2><div className="cert-path-steps"><div className="cert-path-step"><span className={user.baselineCompleted ? 'path-step-complete' : ''}>{user.baselineCompleted ? <CheckCircle2 size={14} /> : '01'}</span><b>Baseline profile</b><small>{user.baselineCompleted ? 'COMPLETE' : 'PENDING'}</small></div><i /><div className="cert-path-step"><span className={user.missionsCompleted >= 1 ? 'path-step-complete' : ''}>{user.missionsCompleted >= 1 ? <CheckCircle2 size={14} /> : '02'}</span><b>Training history</b><small>{Math.min(user.missionsCompleted, 3)} / 3 MISSIONS</small></div><i /><div className="cert-path-step"><span className={user.overallScore >= certThreshold ? 'path-step-complete' : ''}>{user.overallScore >= certThreshold ? <CheckCircle2 size={14} /> : '03'}</span><b>Readiness threshold</b><small>{user.overallScore} / {certThreshold}</small></div><i /><div className="cert-path-step"><span className={earned.length ? 'path-step-complete' : ''}>{earned.length ? <CheckCircle2 size={14} /> : '04'}</span><b>Credential issued</b><small>{earned.length ? 'EARNED' : 'NOT YET EARNED'}</small></div></div><div className="cert-path-footer"><ProgressBar value={Math.min(100, (Number(user.baselineCompleted) * 25) + (Math.min(user.missionsCompleted, 3) / 3 * 45) + (Math.min(user.overallScore, certThreshold) / certThreshold * 30))} /><span>Eligibility progress is based on local training history.</span></div></Card>
  </PageTransition>;
}
